import json

from shared_functions import *


def combine_translated_list_to_string(data, key):
    # Initialize empty strings for concatenation
    combined_text = ""

    # Iterate through each item in the JSON array
    for item in data:
        combined_text += item.get(key, "") + " "  

    # Strip any trailing spaces
    combined_text = combined_text.strip()

    return combined_text


def get_pormpt_for_improvement(text_original: str, text_translated: str, user_instructions: str = "") -> str:
    number_of_issues_to_find = get_params("number_of_issues_to_find")
    if user_instructions:
        style_instruction = (
            f"\n\nThe user has provided the following custom instructions for translation improvement:\n"
            f"{user_instructions}\n"
            "Please generate new custom instructions in the same style as above. "
            "Do not repeat the same instructions, issues or words. "
            "Just use the user's style to create new instructions."
        )
    else:
        style_instruction = (
            "\n\nFor each issue, use a short, concrete instruction. "
            "For example: Instead of using [this word] for translation of [this term in the original_text], use [this word]. "
            "All instructions except for [this term in the original_text] should be in the translation_text's language."
        )

    prompt = f"""
You are tasked with analyzing a translation and providing recommendations for improvement. The goal
is to make the translation more natural and culturally appropriate for speakers of the target
language.

Here is the original text:
<original_text>
{text_original}
</original_text>

Here is the translation:
<translation_text>
{text_translated}
</translation_text>

Analyze the translation carefully, comparing it to the original text.
{style_instruction}

Try not to generalize issues but provide concrete suggestions for improvement and limit your list to no more than {number_of_issues_to_find} issues.

"""
    return prompt


def get_autogenerated_custom_instructions(prompt:str):
    import json
    from openai import OpenAI
    import os
    import dotenv
    dotenv.load_dotenv()
    openai_api_key = os.getenv("OPENAI_API_KEY")
    client = OpenAI(api_key=openai_api_key)
    model = get_params("openai_model")

    system_message = f""" """

    user_message = f"""{prompt}"""


    # gpt-5 only supports default temperature; avoid passing temperature explicitly
    _kwargs = {}
    if not str(model).startswith("gpt-5"):
        _kwargs["temperature"] = 0

    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": f"""{system_message}"""},
            {"role": "user", "content": f"""{user_message}"""}
        ],
        **_kwargs
    )
    logging.info(response.choices[0].message.content)
    res = response.choices[0].message.content



    return res

def main(path):


    setup_logging_with_appinsights(path)
    path_params = naming_convention(path, "params")
    params_curr = json.loads( get_palintext_content(path_params) )

    if params_curr.get("autogenerate_custom_instructions") == "false" or "autogenerate_custom_instructions" not in params_curr:
        logging.info(f"Skipping the generation of custom instructions. {path = }")
        return None

    logging.info(f"Generating custom instructions. {path = }")
    path_translated = naming_convention(path, "translated")
    transcript_translated = json.loads( get_palintext_content(path_translated) )


    # Combine the translated text into a single string
    text_original = combine_translated_list_to_string(transcript_translated, "text")
    text_translated = combine_translated_list_to_string(transcript_translated, get_params("translation_text_key"))

    user_instructions = params_curr.get("custom_instructions", "").strip()
    prompt = get_pormpt_for_improvement(text_original, text_translated, user_instructions)
    autogenerated_custom_instructions = get_autogenerated_custom_instructions(prompt)

    params_curr["custom_instructions"] += f"\n--------------\n{autogenerated_custom_instructions}\n"

    print(f"{params_curr['custom_instructions'] = }")

    save_json_with_upload (path_params, params_curr)

    pass

    # target_lang = get_params("language", path)
    # logging.info(f"Translating to target language: [{target_lang}]")
    # transcript_translated = translate_deepl(transcript_combined, target_lang)


    # path_translated = naming_convention(path, "translated")
    # save_json_with_upload (path_translated, transcript_translated)






    return None



if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('-p', '--path', type=str, required=True, help="Path to the mp3 file")
    args = parser.parse_args()
    main(args.path)



    pass